N_SHOT: 5 # Number of images per class
N_QUERY: 5 # Number of images per class in the query set
N_TRAINING_EPISODES: 2000

BACKBONE_PATH: models/backbone/model_partial_resnet18_fsl_2_class_cuda_100_v1.pth

TRAINING_DATA: C:\DTU\fsl_paper\maritime-fsl\data\data_2023\data_2023
VALIDATION_DATA: C:/DTU/fsl_paper/maritime-fsl/data/data_2023/val_2023/

MODEL_SAVE_PATH: C:\DTU\fsl_paper\maritime-fsl\models\custom\proto_5_v2.pth


data_mean: [0.4609, 0.4467, 0.4413]
data_std: [0.1314, 0.1239, 0.1198]

BACKBONE: custom