IMAGE_SIZE: 224

PROTO_MODEL_PATH: models\pretrained\proto_5_v1.pth

N_SHOT: 5 # Number of images per class
N_QUERY: 5 # Number of images per class in the query set
N_EVALUATION_TASKS: 100
VALIDATION_DATA: C:\DTU\fsl_paper\maritime-fsl\data\data_2023\val_2023_v2

DATA_MEAN: [0.4609, 0.4467, 0.4413]
DATA_STD: [0.1314, 0.1239, 0.1198]